# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r




language: R
before_install:
  - cd R/eudract
sudo: required
cache: packages

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_binary_packages:
  - dplyr
  - magrittr
  - xml2
  - xslt
  - testthat
  - readxl
  - tidyr
  - knitr
  - tidyr
  - rmarkdown
  - covr
  - hms
  - kableextra
  - ps
  - sessioninfo
  - usethis
  - devtools
  - rcpp

r_packages:


notifications:
  email:
    on_success: change
    on_failure: change


after_success:
  - Rscript -e 'library(covr); codecov()'
